/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorahexadecimal;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author paulomatheus
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    Operacoes opera = new Operacoes();
    String letraEquacao = "";
    String numeroEquacao = "";
    String letraHexa = "";
    int numeroHexa = 0;
    int aux = 0;
    boolean inicio = true;
    boolean operacao = false;
    
    //List<String> letraEquacao = new ArrayList();
    
    public HomeScreen() {
        this.setResizable(false);
        this.setTitle("Calculadora Hexadecimal");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnVisor = new javax.swing.JPanel();
        tfConta = new javax.swing.JTextField();
        tfResultado = new javax.swing.JTextField();
        lbIgual = new javax.swing.JLabel();
        pnBotoes = new javax.swing.JPanel();
        btZero = new javax.swing.JButton();
        btUm = new javax.swing.JButton();
        btDois = new javax.swing.JButton();
        btTres = new javax.swing.JButton();
        btQuatro = new javax.swing.JButton();
        btCinco = new javax.swing.JButton();
        btSeis = new javax.swing.JButton();
        btSete = new javax.swing.JButton();
        btOito = new javax.swing.JButton();
        btNove = new javax.swing.JButton();
        btLetraA = new javax.swing.JButton();
        btLetraB = new javax.swing.JButton();
        btLetraC = new javax.swing.JButton();
        btLetraD = new javax.swing.JButton();
        btLetraE = new javax.swing.JButton();
        btLetraF = new javax.swing.JButton();
        btApagar = new javax.swing.JButton();
        btApagarTudo = new javax.swing.JButton();
        btAdicao = new javax.swing.JButton();
        btSubtracao = new javax.swing.JButton();
        btMultiplicacao = new javax.swing.JButton();
        btDivisao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Hexadecimal");
        setBackground(new java.awt.Color(0, 102, 255));

        pnVisor.setBackground(new java.awt.Color(0, 0, 102));
        pnVisor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        tfConta.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        tfConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContaActionPerformed(evt);
            }
        });

        tfResultado.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        lbIgual.setForeground(new java.awt.Color(255, 255, 255));
        lbIgual.setText("      =");

        javax.swing.GroupLayout pnVisorLayout = new javax.swing.GroupLayout(pnVisor);
        pnVisor.setLayout(pnVisorLayout);
        pnVisorLayout.setHorizontalGroup(
            pnVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVisorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnVisorLayout.setVerticalGroup(
            pnVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVisorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnBotoes.setBackground(new java.awt.Color(0, 0, 102));
        pnBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botões", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        btZero.setText("0");
        btZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZeroActionPerformed(evt);
            }
        });

        btUm.setText("1");
        btUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUmActionPerformed(evt);
            }
        });

        btDois.setText("2");
        btDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoisActionPerformed(evt);
            }
        });

        btTres.setText("3");
        btTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTresActionPerformed(evt);
            }
        });

        btQuatro.setText("4");
        btQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuatroActionPerformed(evt);
            }
        });

        btCinco.setText("5");
        btCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCincoActionPerformed(evt);
            }
        });

        btSeis.setText("6");
        btSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeisActionPerformed(evt);
            }
        });

        btSete.setText("7");
        btSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeteActionPerformed(evt);
            }
        });

        btOito.setText("8");
        btOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOitoActionPerformed(evt);
            }
        });

        btNove.setText("9");
        btNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoveActionPerformed(evt);
            }
        });

        btLetraA.setText("A");
        btLetraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLetraAActionPerformed(evt);
            }
        });

        btLetraB.setText("B");
        btLetraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLetraBActionPerformed(evt);
            }
        });

        btLetraC.setText("C");
        btLetraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLetraCActionPerformed(evt);
            }
        });

        btLetraD.setText("D");
        btLetraD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLetraDActionPerformed(evt);
            }
        });

        btLetraE.setText("E");
        btLetraE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLetraEActionPerformed(evt);
            }
        });

        btLetraF.setText("F");
        btLetraF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLetraFActionPerformed(evt);
            }
        });

        btApagar.setText("Apagar");
        btApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarActionPerformed(evt);
            }
        });

        btApagarTudo.setText("Apagar tudo");
        btApagarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarTudoActionPerformed(evt);
            }
        });

        btAdicao.setText("+");
        btAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicaoActionPerformed(evt);
            }
        });

        btSubtracao.setText("-");
        btSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtracaoActionPerformed(evt);
            }
        });

        btMultiplicacao.setText("*");
        btMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplicacaoActionPerformed(evt);
            }
        });

        btDivisao.setText("/");
        btDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBotoesLayout = new javax.swing.GroupLayout(pnBotoes);
        pnBotoes.setLayout(pnBotoesLayout);
        pnBotoesLayout.setHorizontalGroup(
            pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotoesLayout.createSequentialGroup()
                .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addComponent(btLetraC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLetraD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLetraE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLetraF))
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addComponent(btOito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLetraA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLetraB))
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addComponent(btQuatro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCinco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSeis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSete))
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addComponent(btZero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDois)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTres)))
                .addGap(18, 18, 18)
                .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMultiplicacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btApagarTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSubtracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDivisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        pnBotoesLayout.setVerticalGroup(
            pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btDois, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btTres, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btApagarTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnBotoesLayout.createSequentialGroup()
                                .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btSete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pnBotoesLayout.createSequentialGroup()
                                .addComponent(btSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btNove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btOito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLetraA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLetraB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnBotoesLayout.createSequentialGroup()
                        .addComponent(btApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btLetraE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btLetraF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btLetraD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLetraC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuatroActionPerformed
        //Condicao para iniciar a calculadora
        if (inicio) {
            //fazer em tudo
            letraEquacao += "4";
            numeroEquacao += "4" ;
            numeroHexa = Integer.parseInt(letraEquacao, 16);
            System.out.println("NumHexa do inicio =" + numeroHexa);
            letraHexa = Integer.toHexString(numeroHexa);
            tfConta.setText(letraEquacao);
            tfResultado.setText(letraHexa);
        } else {
            //Condicao para ver se a operacao eh de adicao ou subtracao
            if (operacao) {
                System.out.println("NumHexa de adicao = " + numeroHexa);
                //opera.adicao(numeroHexa);
                System.out.println("Retorno de adicao = " + opera.adicao(numeroHexa));
                System.out.println("-----------------------");
                
                
            } else {
                System.out.println("NumHexa de subtracao= " + numeroHexa);
                //opera.subtracao(numeroHexa);
                System.out.println("Retorno de subtracao = " + opera.subtracao(numeroHexa));
                System.out.println("------------------------");
            }
        }
        
    }//GEN-LAST:event_btQuatroActionPerformed

    private void btLetraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLetraAActionPerformed
        String a = "A";
        letraEquacao += a;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btLetraAActionPerformed

    private void btApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarActionPerformed
        try{
            letraEquacao = letraEquacao.substring(0, letraEquacao.length()-1);
            letraHexa = letraHexa.substring(0, letraHexa.length()-1);
            System.out.println(letraEquacao);
            tfConta.setText(letraEquacao);
            tfResultado.setText(letraHexa);
        }catch(StringIndexOutOfBoundsException erro){
            System.out.println(erro);
        }
        
    }//GEN-LAST:event_btApagarActionPerformed

    private void tfContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContaActionPerformed
        
        
        
    }//GEN-LAST:event_tfContaActionPerformed

    private void btZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZeroActionPerformed
        String zero = "0";
        letraEquacao += zero;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btZeroActionPerformed

    private void btUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUmActionPerformed
        String um = "1";
        letraEquacao += um;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btUmActionPerformed

    private void btDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoisActionPerformed
        String dois = "2";
        letraEquacao += dois;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btDoisActionPerformed

    private void btTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTresActionPerformed
        String tres = "3";
        letraEquacao += tres;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btTresActionPerformed

    private void btCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCincoActionPerformed
        String cinco = "5";
        letraEquacao += cinco;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btCincoActionPerformed

    private void btSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeisActionPerformed
        String seis = "6";
        letraEquacao += seis;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btSeisActionPerformed

    private void btSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeteActionPerformed
        String sete = "7";
        letraEquacao += sete;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btSeteActionPerformed

    private void btOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOitoActionPerformed
        String oito = "8";
        letraEquacao += oito;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btOitoActionPerformed

    private void btNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoveActionPerformed
        String nove = "9";
        int vc = 9;
        letraEquacao += nove;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btNoveActionPerformed

    private void btLetraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLetraBActionPerformed
        String b = "B";
        letraEquacao += b;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btLetraBActionPerformed

    private void btLetraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLetraCActionPerformed
        String c = "C";
        letraEquacao += c;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        System.out.println(numeroHexa);
        letraHexa = Integer.toHexString(numeroHexa);
        System.out.println(letraHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btLetraCActionPerformed

    private void btLetraDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLetraDActionPerformed
        String d = "D";
        letraEquacao += d;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btLetraDActionPerformed

    private void btLetraEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLetraEActionPerformed
        String e = "E";
        letraEquacao += e;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btLetraEActionPerformed

    private void btLetraFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLetraFActionPerformed
        String f = "F";
        letraEquacao += f;
        numeroHexa = Integer.parseInt(letraEquacao, 16);
        System.out.println(numeroHexa);
        letraHexa = Integer.toHexString(numeroHexa);
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btLetraFActionPerformed

    private void btApagarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarTudoActionPerformed
        inicio = true;
        operacao = true;
        letraEquacao = "";
        letraHexa = "";
        numeroHexa = 0;
        //valor
        tfConta.setText(letraEquacao);
        tfResultado.setText(letraHexa);
    }//GEN-LAST:event_btApagarTudoActionPerformed

    private void btAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicaoActionPerformed
        inicio = false;
        operacao = true;
        System.out.println("-----------" +operacao+ "----------------");
        String mais = "+";
        letraEquacao += mais;
        tfConta.setText(letraEquacao);
        
    }//GEN-LAST:event_btAdicaoActionPerformed

    private void btSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtracaoActionPerformed
        inicio = false;
        operacao = false;
        System.out.println("-----------" +operacao+ "----------------");
        String menos = "-";
        letraEquacao += menos;
        tfConta.setText(letraEquacao);
    }//GEN-LAST:event_btSubtracaoActionPerformed

    private void btMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplicacaoActionPerformed
        String multiplicacao = "*";
        letraEquacao += multiplicacao;
        tfConta.setText(letraEquacao);
    }//GEN-LAST:event_btMultiplicacaoActionPerformed

    private void btDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivisaoActionPerformed
        String divisao = "/";
        letraEquacao += divisao;
        tfConta.setText(letraEquacao);
    }//GEN-LAST:event_btDivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicao;
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btApagarTudo;
    private javax.swing.JButton btCinco;
    private javax.swing.JButton btDivisao;
    private javax.swing.JButton btDois;
    private javax.swing.JButton btLetraA;
    private javax.swing.JButton btLetraB;
    private javax.swing.JButton btLetraC;
    private javax.swing.JButton btLetraD;
    private javax.swing.JButton btLetraE;
    private javax.swing.JButton btLetraF;
    private javax.swing.JButton btMultiplicacao;
    private javax.swing.JButton btNove;
    private javax.swing.JButton btOito;
    private javax.swing.JButton btQuatro;
    private javax.swing.JButton btSeis;
    private javax.swing.JButton btSete;
    private javax.swing.JButton btSubtracao;
    private javax.swing.JButton btTres;
    private javax.swing.JButton btUm;
    private javax.swing.JButton btZero;
    private javax.swing.JLabel lbIgual;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnVisor;
    private javax.swing.JTextField tfConta;
    private javax.swing.JTextField tfResultado;
    // End of variables declaration//GEN-END:variables
}
